import "@/styles/dashboard.css";
import "@/styles/recommend.css";
import Menu from "@/components/menu";

export default function Recommend() {
  return (
    <>
      <div id="dashboard">
        <Menu />
        <div className="dashboard__function">
          <table>
            <tbody>
              <tr>
                <th>Time</th>
                <th>Monday</th>
                <th>Tuesday</th>
                <th>Wednesday</th>
                <th>Thursday</th>
                <th>Friday</th>
                <th>Saturday</th>
                <th>Sunday</th>
              </tr>
              <tr>
                <td>0-1h</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
              </tr>
              <tr>
                <td>1-2h</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
              </tr>
              <tr>
                <td>2-3h</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
              </tr>
              <tr>
                <td>3-4h</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
              </tr>
              <tr>
                <td>4-5h</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
              </tr>
              <tr>
                <td>5-6h</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
              </tr>
              <tr>
                <td>6-7h</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
              </tr>
              <tr>
                <td>7-8h</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
              </tr>
              <tr>
                <td>8-9h</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
              </tr>
              <tr>
                <td>9-10h</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
              </tr>
              <tr>
                <td>10-11h</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
              </tr>
              <tr>
                <td>11-12h</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
                <td>On</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
}
